In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report

In [14]:
from time import time
from sklearn.metrics import f1_score

In [2]:
positive=pd.read_csv("tweetsp.csv", sep=",",error_bad_lines=False)

b'Skipping line 169: expected 1 fields, saw 4\nSkipping line 266: expected 1 fields, saw 2\nSkipping line 314: expected 1 fields, saw 2\nSkipping line 361: expected 1 fields, saw 2\nSkipping line 388: expected 1 fields, saw 2\nSkipping line 796: expected 1 fields, saw 2\nSkipping line 873: expected 1 fields, saw 3\n'


In [3]:
negative=pd.read_csv("tweetsn.csv", sep=",",error_bad_lines=False)

b'Skipping line 13: expected 1 fields, saw 4\nSkipping line 23: expected 1 fields, saw 5\nSkipping line 25: expected 1 fields, saw 2\nSkipping line 64: expected 1 fields, saw 4\nSkipping line 68: expected 1 fields, saw 4\nSkipping line 82: expected 1 fields, saw 4\nSkipping line 94: expected 1 fields, saw 5\nSkipping line 96: expected 1 fields, saw 2\nSkipping line 138: expected 1 fields, saw 9\nSkipping line 150: expected 1 fields, saw 3\nSkipping line 163: expected 1 fields, saw 9\nSkipping line 229: expected 1 fields, saw 2\nSkipping line 280: expected 1 fields, saw 2\nSkipping line 365: expected 1 fields, saw 2\nSkipping line 463: expected 1 fields, saw 2\nSkipping line 565: expected 1 fields, saw 3\nSkipping line 566: expected 1 fields, saw 3\nSkipping line 606: expected 1 fields, saw 2\nSkipping line 690: expected 1 fields, saw 2\nSkipping line 831: expected 1 fields, saw 3\nSkipping line 967: expected 1 fields, saw 2\n'


In [4]:
label_neg= pd.Series(0,index=range(negative.shape[0]))


In [5]:
label_pos= pd.Series(1,index=range(positive.shape[0]))

In [6]:
y=[label_pos,label_neg]
y = pd.concat(y)
y

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
912    0
913    0
914    0
915    0
916    0
917    0
918    0
919    0
920    0
921    0
922    0
923    0
924    0
925    0
926    0
927    0
928    0
929    0
930    0
931    0
932    0
933    0
934    0
935    0
936    0
937    0
938    0
939    0
940    0
941    0
Length: 1935, dtype: int64

In [7]:
x=[positive,negative]
x = pd.concat(x)
x=x['text']

In [8]:
from sklearn.model_selection import cross_val_score
 

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(min_df=2, ngram_range=(1, 2),  strip_accents='unicode' ,   norm='l2')
X = vectorizer.fit_transform(x)


In [10]:
def train_classifier(clf, X_train, y_train):
    ''' Fits a classifier to the training data. '''
    
    # Start the clock, train the classifier, then stop the clock
    start = time()
    clf.fit(X_train, y_train)
    end = time()
    
    # Print the results
    print ("Trained model in {:.4f} seconds".format(end - start))

    
def predict_labels(clf, features, target):
    ''' Makes predictions using a fit classifier based on F1 score. '''
    
    # Start the clock, make predictions, then stop the clock
    start = time()
    y_pred = clf.predict(features)
    end = time()
    
    # Print and return results
    print ("Made predictions in {:.4f} seconds.".format(end - start))
    return f1_score(target.values, y_pred, pos_label=1)


def train_predict(clf, X_train, y_train, X_test, y_test):
    ''' Train and predict using a classifer based on F1 score. '''
    
    # Indicate the classifier and the training set size
    print ("Training a {} using a training set size of {}. . .".format(clf.__class__.__name__, X_train.shape[0]))
    
    # Train the classifier
    train_classifier(clf, X_train, y_train)
    
    # Print the results of prediction for both training and testing
    print ("F1 score for training set: {:.4f}.".format(predict_labels(clf, X_train, y_train)))
    print ("F1 score for test set: {:.4f}.".format(predict_labels(clf, X_test, y_test)))

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [15]:
# TODO: Import the three supervised learning models from sklearn
# from sklearn import model_A
# from sklearn import model_B
# from sklearn import model_C
from sklearn.naive_bayes import MultinomialNB

from sklearn import tree
from sklearn.svm import SVC
# TODO: Initialize the three models
clf_nbays = MultinomialNB()
clf_DT = tree.DecisionTreeClassifier(max_depth=500)
clf_svm = SVC()



# TODO: Set up the training set sizes
X_train_100 = X_train[:1000]
y_train_100 = y_train[:1000]


X_train_all = X_train
y_train_all = y_train

# TODO: Execute the 'train_predict' function for each classifier and each training set size
print( "NB")
print( "NB -100")
train_predict(clf_nbays, X_train_100, y_train_100, X_test, y_test)

print( "NB -all")
train_predict(clf_nbays, X_train_all, y_train_all, X_test, y_test)





NB
NB -100
Training a MultinomialNB using a training set size of 1000. . .
Trained model in 0.0100 seconds
Made predictions in 0.0000 seconds.
F1 score for training set: 0.9551.
Made predictions in 0.0000 seconds.
F1 score for test set: 0.8468.
NB -all
Training a MultinomialNB using a training set size of 1296. . .
Trained model in 0.0000 seconds
Made predictions in 0.0100 seconds.
F1 score for training set: 0.9488.
Made predictions in 0.0000 seconds.
F1 score for test set: 0.8642.


In [18]:
print( "DT")
print( "DT -100")
train_predict(clf_DT, X_train_100, y_train_100, X_test, y_test)

print( "DT -all")
train_predict(clf_DT, X_train_all, y_train_all, X_test, y_test)

DT
DT -100
Training a DecisionTreeClassifier using a training set size of 1000. . .
Trained model in 0.3300 seconds
Made predictions in 0.0200 seconds.
F1 score for training set: 0.9875.
Made predictions in 0.0000 seconds.
F1 score for test set: 0.7643.
DT -all
Training a DecisionTreeClassifier using a training set size of 1296. . .
Trained model in 0.1300 seconds
Made predictions in 0.0000 seconds.
F1 score for training set: 0.9879.
Made predictions in 0.0000 seconds.
F1 score for test set: 0.7770.


In [19]:
print( "SVM")
print( "SVM -100")
train_predict(clf_svm, X_train_100, y_train_100, X_test, y_test)

print( "SVM-300")
train_predict(clf_svm, X_train_all, y_train_all, X_test, y_test)

SVM
SVM -100
Training a SVC using a training set size of 1000. . .
Trained model in 0.1200 seconds
Made predictions in 0.0800 seconds.
F1 score for training set: 0.6894.
Made predictions in 0.0600 seconds.
F1 score for test set: 0.6770.
SVM-300
Training a SVC using a training set size of 1296. . .
Trained model in 0.1600 seconds
Made predictions in 0.1500 seconds.
F1 score for training set: 0.6789.
Made predictions in 0.0700 seconds.
F1 score for test set: 0.6770.


In [20]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X, y)
y_nbays_pred = clf.predict(X)

In [21]:

scores = cross_val_score(clf, X, y, cv=5)
scores 

array([ 0.82731959,  0.78092784,  0.7622739 ,  0.86528497,  0.88601036])

In [22]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import confusion_matrix
clf = SGDClassifier(alpha=.0001, n_iter=70).fit(X, y)




C:\Users\MRshad\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:73: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


In [23]:
scores = cross_val_score(clf, X, y, cv=5)
scores 



array([ 0.73969072,  0.79639175,  0.77777778,  0.80569948,  0.82124352])

In [25]:
from sklearn.svm import LinearSVC
svm_classifier = LinearSVC().fit(X, y)




In [26]:
scores = cross_val_score(clf, X, y, cv=5)
scores 

array([ 0.7371134 ,  0.79896907,  0.7751938 ,  0.80829016,  0.82124352])

In [29]:
from sklearn.ensemble import RandomForestClassifier
RF_clf = RandomForestClassifier(n_estimators=10).fit(X_train, y_train)
y_rdm_forest_pred = RF_clf.predict(X_test)


In [30]:

print (classification_report(y_test, y_rdm_forest_pred))


             precision    recall  f1-score   support

          0       0.77      0.88      0.82       312
          1       0.86      0.74      0.80       327

avg / total       0.82      0.81      0.81       639



In [31]:
cm = confusion_matrix(y_test, y_rdm_forest_pred)
print (cm)

[[274  38]
 [ 84 243]]


In [32]:
print(X[0])

  (0, 1528)	1.0


In [34]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train, y_train)
y_nbays_pred = clf.predict(X_test)

In [35]:
print( classification_report(y_test, y_nbays_pred))

             precision    recall  f1-score   support

          0       0.90      0.79      0.84       312
          1       0.82      0.91      0.86       327

avg / total       0.86      0.85      0.85       639

